### PR TITLE
Transition from document.write to document.createElement [PD-2659]

### PR DESCRIPTION
**Pull request by tdphillips**
The diff for this is 46 files but half of them are duplicated.

If you're reviewing this, framework/js and framework/js/secure are completely identical with the exception of def.ui.core.js.

### CODE REVIEW

**Comment by darrint** [comment]
Is this the new correct practice?

**Comment by tdphillips** [comment]
https://directemployersfoundation.atlassian.net/browse/PD-2659

**Comment by tdphillips** [comment]
I'll leave it to those who know JS better than I. If this is wrong, I can trash the branch and we can forget this ever happened.

**Comment by darrint** [comment]
It looks ok to me. I'm not sure how I'd figure out how to test all of it.

**Comment by tdphillips** [comment]
@fezick should probably take a look. We had a small amount of discussion regarding if these being added as the first scripts on the page would be an issue.

**Pull request merged**
